### ISSUE TITLE
benchmark问题

### ISSUE THREAD

**Issue by tomlee0201** [go-chassis/go-chassis#308]
我们使用benchmark测试，发现如下问题

```
2018-08-01 10:05:32.313 +08:00 INFO highway/highway_base_client.go:77 GetClient from new open addr:127.0.0.1:8082
2018-08-01 10:05:32.322 +08:00 ERROR highway/highway_msgobj.go:238 Unmarshal response body  failed error: proto: invalid UTF-8 string
2018-08-01 10:05:32.322 +08:00 ERROR highway/highway_msgobj.go:201 Frame head error. error: Invalid magicID
Error have occured:  Expected Msg: , But: 
2018-08-01 10:05:32.331 +08:00 ERROR highway/highway_msgobj.go:238 Unmarshal response body  failed error: proto: invalid UTF-8 string
2018-08-01 10:05:32.331 +08:00 ERROR highway/highway_msgobj.go:201 Frame head error. error: Invalid magicID
Error have occured:  Expected Msg: , But: 
2018-08-01 10:05:32.336 +08:00 ERROR highway/highway_msgobj.go:238 Unmarshal response body  failed error: proto: invalid UTF-8 string
2018-08-01 10:05:32.337 +08:00 ERROR highway/highway_msgobj.go:201 Frame head error. error: Invalid magicID
Error have occured:  Expected Msg: , But: 
2018-08-01 10:05:32.349 +08:00 ERROR highway/highway_msgobj.go:238 Unmarshal response body  failed error: proto: invalid UTF-8 string
2018-08-01 10:05:32.349 +08:00 ERROR highway/highway_msgobj.go:201 Frame head error. error: Invalid magicID
Error have occured:  Expected Msg: , But: 
2018-08-01 10:05:32.457 +08:00 ERROR highway/highway_msgobj.go:238 Unmarshal response body  failed error: proto: invalid UTF-8 string
2018-08-01 10:05:32.457 +08:00 ERROR highway/highway_msgobj.go:201 Frame head error. error: Invalid magicID
Error have occured:  Expected Msg: , But: 
2018-08-01 10:05:32.462 +08:00 ERROR highway/highway_msgobj.go:238 Unmarshal response body  failed error: proto: invalid UTF-8 string
2018-08-01 10:05:32.462 +08:00 ERROR highway/highway_msgobj.go:201 Frame head error. error: Invalid magicID
Error have occured:  Expected Msg: , But: 
2018-08-01 10:05:32.465 +08:00 ERROR highway/highway_msgobj.go:238 Unmarshal response body  failed error: proto: invalid UTF-8 string
2018-08-01 10:05:32.466 +08:00 ERROR highway/highway_msgobj.go:201 Frame head error. error: Invalid magicID
Error have occured:  Expected Msg: , But: 
2018-08-01 10:05:32.491 +08:00 ERROR highway/highway_msgobj.go:238 Unmarshal response body  failed error: proto: invalid UTF-8 string
2018-08-01 10:05:32.491 +08:00 ERROR highway/highway_msgobj.go:201 Frame head error. error: Invalid magicID
Error have occured:  Expected Msg: , But: 
2018-08-01 10:05:32.497 +08:00 ERROR highway/highway_msgobj.go:238 Unmarshal response body  failed error: proto: invalid UTF-8 string
2018-08-01 10:05:32.497 +08:00 ERROR highway/highway_msgobj.go:201 Frame head error. error: Invalid magicID
Error have occured:  Expected Msg: , But: 
2018-08-01 10:05:32.516 +08:00 ERROR highway/highway_msgobj.go:238 Unmarshal response body  failed error: proto: invalid UTF-8 string
2018-08-01 10:05:32.516 +08:00 ERROR highway/highway_msgobj.go:201 Frame head error. error: Invalid magicID
Error have occured:  Expected Msg: , But: 
2018-08-01 10:05:32.555 +08:00 ERROR highway/highway_msgobj.go:238 Unmarshal response body  failed error: proto: invalid UTF-8 string
2018-08-01 10:05:32.555 +08:00 ERROR highway/highway_msgobj.go:201 Frame head error. error: Invalid magicID
Error have occured:  Expected Msg: , But: 
2018-08-01 10:05:32.620 +08:00 ERROR highway/highway_msgobj.go:238 Unmarshal response body  failed error: proto: invalid UTF-8 string
2018-08-01 10:05:32.620 +08:00 ERROR highway/highway_msgobj.go:201 Frame head error. error: Invalid magicID
Error have occured:  Expected Msg: , But: 
2018-08-01 10:05:32.630 +08:00 ERROR highway/highway_msgobj.go:238 Unmarshal response body  failed error: proto: invalid UTF-8 string
2018-08-01 10:05:32.630 +08:00 ERROR highway/highway_msgobj.go:201 Frame head error. error: Invalid magicID
Error have occured:  Expected Msg: , But: 
2018-08-01 10:05:32.630 +08:00 ERROR highway/highway_base_client.go:242 AsyncSendMsg err: error: write tcp 127.0.0.1:49353->127.0.0.1:8082: use of closed network connection
2018-08-01 10:05:32.630 +08:00 ERROR handler/transport_handler.go:47 Call got Error error: write tcp 127.0.0.1:49353->127.0.0.1:8082: use of closed network connection
panic: write tcp 127.0.0.1:49353->127.0.0.1:8082: use of closed network connection

goroutine 92 [running]:
main.Call(0xbed0633b12d012be, 0x178d650, 0x4fbac20, 0xc42000c240, 0x0, 0x0, 0x0, 0x4a158c6, 0x7, 0x4e20, ...)
	/Users/heavyrainlee/go/src/github.com/go-chassis/go-chassis/benchmark/client/main.go:141 +0x9ce
created by main.main
	/Users/heavyrainlee/go/src/github.com/go-chassis/go-chassis/benchmark/client/main.go:115 +0x5e4
```

测试使用的是highway，测试方法就是修改benchmark/client/conf/test.yaml，把最后一行改为
```
protocol: highway
```

复现概率为偶现，10次能出1次的大概概率

**Comment by tianxiaoliang** [comment]
we will check

**Comment by xixiloveyou** [comment]
@tianxiaoliang 这个bug，0.7版还是有问题，你们有计划修改时间吗？

**Comment by tianxiaoliang** [comment]
本月内修复

**Comment by tianxiaoliang** [comment]
是否可以问下，为何不考虑使用http协议而选择rpc呢

**Comment by xixiloveyou** [comment]
@tianxiaoliang 主要是想利用rpc的性能优势

**Comment by tianxiaoliang** [comment]
ok，目前highway的性能并没有比http性能高，也计划在今年内删除，改用新的rpc方案。
我推荐使用http，另外是否有足够证明通信协议拖了业务代码的后腿，以我的经验来说一般框架的性能和业务代码的性能根本不是一个数量级，比如通信给你带来的延迟是1ms，而业务代码延迟是100s，那么1ms这个数量级可以忽略。

**Comment by heavyrain2012** [comment]
HI，我们项目在开发时选用了highway，计划年底上线，我现在需要再确认一下，你们是要放弃highway了吗？如果放弃新的rpc方案什么时候能出来

**Comment by tianxiaoliang** [comment]
highway已经不维护了，新的rpc方案待定，也许是原生net/rpc，也许是grpc。目前是全力支持http场景

**Comment by tomlee0201** [comment]
highway有什么问题吗，我们可不可以继续使用？

**Comment by tianxiaoliang** [comment]
not production ready

tomlee0201 <notifications@github.com> 于2018年10月16日周二 上午11:44写道：

**Comment by tianxiaoliang** [comment]
实现了grpc协议，可以看下examples/grpc
