### ISSUE TITLE
java项目使用DiscoveryTree 获取go服务的实例列表失败，java服务无问题

### ISSUE THREAD

**Issue by Fang57** [go-chassis/go-chassis#824]
DiscoveryTree discoveryTree = new DiscoveryTree();
DiscoveryContext context = new DiscoveryContext();
VersionedCache serversVersionedCache = discoveryTree.discovery(context, RegistryUtils.getAppId(),
                "Service", "0.0.0.0+");
List<String> enpoints = serversVersionedCache.data();

go-chassis版本 v1.4.1

**Comment by tianxiaoliang** [comment]
请看下版本策略https://github.com/go-chassis/go-chassis/wiki/%E7%89%88%E6%9C%AC%E7%AD%96%E7%95%A5

升级到1.8.2，然后我们看下是不是有什么问题

而且你没给错误日志

**Comment by Fang57** [comment]
v1.8.2无问题

**Comment by Fang57** [comment]
错误日志：
org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: Parse swagger from content failed, 
	at org.apache.servicecomb.swagger.SwaggerUtils.parseSwagger(SwaggerUtils.java:71) ~[swagger-generator-core-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.core.definition.SchemaUtils.parseSwagger(SchemaUtils.java:48) ~[java-chassis-core-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory.loadSwagger(ConsumerSchemaFactory.java:81) ~[java-chassis-core-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory.createSchema(ConsumerSchemaFactory.java:58) ~[java-chassis-core-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory.createSchema(ConsumerSchemaFactory.java:33) ~[java-chassis-core-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.getOrCreateSchema(AbstractSchemaFactory.java:58) ~[java-chassis-core-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory.createConsumerSchema(ConsumerSchemaFactory.java:48) ~[java-chassis-core-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.core.definition.MicroserviceVersionMeta.<init>(MicroserviceVersionMeta.java:45) ~[java-chassis-core-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.core.definition.MicroserviceVersionMetaFactory.create(MicroserviceVersionMetaFactory.java:38) ~[java-chassis-core-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.lambda$setInstances$0(MicroserviceVersions.java:188) ~[service-registry-1.2.0.B011.jar:1.2.0.B011]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_212]
	at org.apache.servicecomb.foundation.common.concurrent.ConcurrentHashMapEx.computeIfAbsent(ConcurrentHashMapEx.java:56) ~[foundation-common-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.setInstances(MicroserviceVersions.java:187) ~[service-registry-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.safeSetInstances(MicroserviceVersions.java:167) ~[service-registry-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.pullInstances(MicroserviceVersions.java:162) ~[service-registry-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.submitPull(MicroserviceVersions.java:134) ~[service-registry-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceManager.lambda$getOrCreateMicroserviceVersions$0(MicroserviceManager.java:55) ~[service-registry-1.2.0.B011.jar:1.2.0.B011]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_212]
	at org.apache.servicecomb.foundation.common.concurrent.ConcurrentHashMapEx.computeIfAbsent(ConcurrentHashMapEx.java:56) ~[foundation-common-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceManager.getOrCreateMicroserviceVersions(MicroserviceManager.java:53) ~[service-registry-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceManager.getOrCreateMicroserviceVersionRule(MicroserviceManager.java:80) ~[service-registry-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.serviceregistry.consumer.AppManager.getOrCreateMicroserviceVersionRule(AppManager.java:67) ~[service-registry-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.serviceregistry.cache.InstanceCacheManagerNew.getOrCreateVersionedCache(InstanceCacheManagerNew.java:39) ~[service-registry-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.serviceregistry.discovery.DiscoveryTree.discovery(DiscoveryTree.java:121) ~[service-registry-1.2.0.B011.jar:1.2.0.B011]
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1626) [?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at org.apache.servicecomb.swagger.SwaggerUtils.correctResponses(SwaggerUtils.java:110) ~[swagger-generator-core-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.swagger.SwaggerUtils.correctResponses(SwaggerUtils.java:141) ~[swagger-generator-core-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.swagger.SwaggerUtils.internalParseSwagger(SwaggerUtils.java:101) ~[swagger-generator-core-1.2.0.B011.jar:1.2.0.B011]
	at org.apache.servicecomb.swagger.SwaggerUtils.parseSwagger(SwaggerUtils.java:69) ~[swagger-generator-core-1.2.0.B011.jar:1.2.0.B011]
	... 33 more

**Comment by tianxiaoliang** [comment]
需要你对比下core/registry core/router 等包的git变更或者读RN看下变更
