### ISSUE TITLE
restful server handler chain copy bug, when muilt request copy handle chain, will panic

### ISSUE THREAD

**Issue by yankooo** [go-chassis/go-chassis#875]
**Describe the bug**
restful 服务在进行handler链拷贝的时候，会出现并发问题：

https://github.com/go-chassis/go-chassis/blob/c410e5a49eb33a29f8ba5af60eb03064be55e78a/server/restful/router.go#L139

``` go
// Chain struct for service and handlers
type Chain struct {
	ServiceType string
	Name        string
	Handlers    []Handler
}

...

c := &handler.Chain{}
*c = *originChain
c.AddHandler(newHandler(handleFunc, bs, opts))
```
Handlers是一个slice，当并发处理到 `*c = *originChain`，同时进行下一行的append操作，可能会导致后一个请求的handler覆盖前一个请求的append操作，导致并发问题。

具体实际的场景，比如originChain因为append了3个handler，所以len为3， cap为4。问题就在于这里，并发append的时候，两个协程同时发现底层数组还有一个位置可以写，都往最后一个位置写，然后再进行内存拷贝，这时候就会出现`DATA RACE`。

**Version of go chassis**

``` shell
v2.0.0-alpha.3 
v2.0.0-alpha.2
```

**Log**
```
fatal error: concurrent map writes

goroutine 518470 [running]:
runtime.throw(0x2e063c3, 0x15)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc01c8251a8 sp=0xc01c825178 pc=0xef8962
runtime.mapassign_faststr(0x2ab5d20, 0xc01c8c1aa0, 0x2dea8f5, 0x6, 0x2)
	/usr/local/go/src/runtime/map_faststr.go:291 +0x40f fp=0xc01c825210 sp=0xc01c8251a8 pc=0xede0bf
github.com/emicklei/go-restful.(*Request).SetAttribute(...)
	/root/go/pkg/mod/github.com/emicklei/go-restful@v2.12.0+incompatible/request.go:107
github.com/go-chassis/go-chassis/server/restful.Invocation2HTTPRequest(0xc020183e60, 0xc01c8c19e0)
...
net/http.(*conn).serve(0xc0201f2e60, 0x31e02e0, 0xc01ca3f180)
	/usr/local/go/src/net/http/server.go:1878 +0x851 fp=0xc01c825fc8 sp=0xc01c825d20 pc=0x11c5f81
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc01c825fd0 sp=0xc01c825fc8 pc=0xf28eb1
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
	
goroutine 518462 [running]:
runtime.throw(0x2e063c3, 0x15)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc01ff4b1a8 sp=0xc01ff4b178 pc=0xef8962
runtime.mapassign_faststr(0x2ab5d20, 0xc01c8c1aa0, 0x2dea8f5, 0x6, 0x2)
	/usr/local/go/src/runtime/map_faststr.go:291 +0x40f fp=0xc01ff4b210 sp=0xc01ff4b1a8 pc=0xede0bf
github.com/emicklei/go-restful.(*Request).SetAttribute(...)
	/root/go/pkg/mod/github.com/emicklei/go-restful@v2.12.0+incompatible/request.go:107
github.com/go-chassis/go-chassis/server/restful.Invocation2HTTPRequest(0xc020334d80, 0xc01c8c19e0)
...
net/http.(*conn).serve(0xc0201bc3c0, 0x31e02e0, 0xc020016ec0)
	/usr/local/go/src/net/http/server.go:1878 +0x851 fp=0xc01ff4bfc8 sp=0xc01ff4bd20 pc=0x11c5f81
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc01ff4bfd0 sp=0xc01ff4bfc8 pc=0xf28eb1
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Comment by tianxiaoliang** [comment]
对于这个问题是否有修复建议，怎么修复更合适

**Comment by tianxiaoliang** [comment]
可以发给我错误信息么

**Comment by yankooo** [comment]
日志贴上了，建议替换 `*c = *originChain` 这种拷贝方式，这种写法，c.Handlers和originChain.Handlers不会立刻分配一个新的底层数组，写一个拷贝的工具函数，为Handlers这个切片分配内存。

**Comment by tianxiaoliang** [comment]
似乎是
```go
// Invocation2HTTPRequest convert invocation back to http request, set down all meta data
func Invocation2HTTPRequest(inv *invocation.Invocation, req *restful.Request) {
	for k, v := range inv.Metadata {
		req.SetAttribute(k, v.(string))
	}
	m := common.FromContext(inv.Ctx)
	for k, v := range m {
		req.Request.Header.Set(k, v)
	}

}
```

req.SetAttribute(k, v.(string))

这句引起的问题

**Comment by yankooo** [comment]
源头是因为originChain这个共享变量的拷贝，不然正常情况 req.SetAttribute(k, v.(string)) 这都是在独立协程中完成，不会引发map并发写

**Comment by tianxiaoliang** [comment]
嗯 ，那就保证每次创建新的chain，会面临性能下降，但是现在先规避吧，你提个PR。感谢

**Comment by tianxiaoliang** [comment]
我看了下 这里写的内存copy确实不对，直接把139行删除，每次都create一个新的chain即可

**Comment by tianxiaoliang** [comment]
感谢贡献
